# Generated by Django 6.0.6 on 2026-06-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiya', models.CharField(default='', max_length=200, verbose_name='Ism va Familiya')),
                ('telefon', models.CharField(default='', max_length=20, verbose_name='Telefon raqami')),
                ('manzil', models.CharField(default='', max_length=200, verbose_name='Manzil (Andijon tumani)')),
                ('xabar', models.TextField(blank=True, default='', verbose_name="Qo'shimcha xabar")),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('korildi', models.BooleanField(default=False, verbose_name="Ko'rildi")),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': '📩 Buyurtmalar',
                'ordering': ['-yaratilgan_vaqt'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(default='', max_length=300, verbose_name='Savol')),
                ('javob', models.TextField(default='', verbose_name='Javob')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('faol', models.BooleanField(default=True, verbose_name="Saytda ko'rsatilsin")),
            ],
            options={
                'verbose_name': 'Savol-Javob',
                'verbose_name_plural': '❓ Savol-Javoblar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='⭐', max_length=10, verbose_name='Emoji belgisi')),
                ('sarlavha', models.CharField(default='', max_length=100, verbose_name='Sarlavha')),
                ('matn', models.TextField(default='', verbose_name='Tavsif matni')),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('faol', models.BooleanField(default=True, verbose_name="Saytda ko'rsatilsin")),
            ],
            options={
                'verbose_name': 'Afzallik',
                'verbose_name_plural': '⭐ Afzalliklar',
                'ordering': ['tartib'],
            },
        ),
    ]
