# Generated by Django 6.0.6 on 2026-06-07 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotJavob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(verbose_name='Javob matni')),
                ('vaqt', models.DateTimeField(auto_now_add=True, verbose_name='Javob vaqti')),
                ('korildi', models.BooleanField(default=False, verbose_name="Mijoz ko'rdimi")),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javoblar', to='main.contactmessage', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Bot Javob',
                'verbose_name_plural': '💬 Bot Javoblar',
                'ordering': ['vaqt'],
            },
        ),
    ]
