# Generated by Django 6.0.6 on 2026-06-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_botjavob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🏠', max_length=10, verbose_name='Emoji belgisi')),
                ('nomi', models.CharField(default='', max_length=100, verbose_name='Soha nomi (Masalan: Uylar)')),
                ('matn', models.TextField(default='', verbose_name="Qisqacha ta'rifi")),
                ('tartib', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('faol', models.BooleanField(default=True, verbose_name="Saytda ko'rsatilsin")),
            ],
            options={
                'verbose_name': "Qo'llash sohasi",
                'verbose_name_plural': "🏢 Qo'llash sohalari",
                'ordering': ['tartib'],
            },
        ),
    ]
